import type { Metadata } from "next"
import { ThemeProvider } from "@/components/theme-provider"
import { Inter } from "next/font/google"
import "./globals.css"
import { ModeToggle } from "@/components/mode-toggle"

import { BreadcrumbWrapper } from "@/components/ui/breadcrumb-wrapper"

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="container p-4 text-right">
            <ModeToggle />
            <BreadcrumbWrapper />
          </header>
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}
